<a href="https://colab.research.google.com/github/badalm06/Numpy/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Creating numpy/n-d arrays
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(arr2)

numpy.ndarray

In [12]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr7 = np.arange(1,10,2)
arr7

array([1, 3, 5, 7, 9])

In [27]:
arr8 = np.linspace(10,20,5)
arr8

array([10. , 12.5, 15. , 17.5, 20. ])

In [30]:
arr1.shape

(5,)

In [31]:
arr3.shape

(2, 3)

In [32]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
arr9.shape

(2, 2, 2)

In [34]:
arr9.ndim

3

In [35]:
arr3.ndim

2

In [36]:
arr1.ndim

1

In [39]:
arr1.size

5

In [38]:
arr9.size

8

In [40]:
arr9.dtype

dtype('int64')

In [ ]:
arr1.shape

(5,)

In [ ]:
arr3.shape

(2, 3)

In [ ]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr9.shape

(2, 2, 2)

In [44]:
arr10 = np.array([1,2,3,4,5])
arr10

array([1, 2, 3, 4, 5])

In [45]:
arr10.dtype

dtype('int64')

In [46]:
arr10.astype('float')

array([1., 2., 3., 4., 5.])