<a href="https://colab.research.google.com/github/badalm06/Numpy/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Creating numpy/n-d arrays
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr7 = np.arange(1,10,2)
arr7

array([1, 3, 5, 7, 9])

In [ ]:
arr8 = np.linspace(10,20,5)
arr8

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
arr1.shape

(5,)

In [ ]:
arr3.shape

(2, 3)

In [ ]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr9.shape

(2, 2, 2)

In [ ]:
arr9.ndim

3

In [ ]:
arr3.ndim

2

In [ ]:
arr1.ndim

1

In [ ]:
arr1.size

5

In [ ]:
arr9.size

8

In [ ]:
arr9.dtype

dtype('int64')

In [ ]:
arr10 = np.array([1,2,3,4,5])
arr10

array([1, 2, 3, 4, 5])

In [ ]:
arr10.dtype

dtype('int64')

In [ ]:
arr10.astype('float')

array([1., 2., 3., 4., 5.])

In [ ]:
lista = range(100)
arr11 = np.arange(100)

In [2]:
import sys

In [ ]:
print(sys.getsizeof(25)*len(lista))

2800


In [ ]:
print(arr11.itemsize*arr11.size)

800


In [3]:
import time

In [ ]:
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()
c = [(x,y) for x,y in zip (x,y)]

print(time.time() - start_time)


2.095133066177368


In [10]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start_time = time.time()
c = a+b

print(time.time()-start_time)


0.01564335823059082


In [7]:
arr13 = np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr13[:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
arr13[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [8]:
arr13[4:,2:]

array([[18, 19],
       [22, 23]])

In [9]:
for i in np.nditer(arr13):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [11]:
arr14 = np.array([1,2,3,4,5,6])
arr15 = np.array([4,5,6,7,8,9])

In [12]:
arr14-arr15

array([-3, -3, -3, -3, -3, -3])

In [13]:
arr14*arr15

array([ 4, 10, 18, 28, 40, 54])

In [16]:
arr14.dot(arr15)

np.int64(154)

In [14]:
arr16 = np.arange(6).reshape(2,3)
arr17 = np.arange(6).reshape(3,2)

In [15]:
arr16.dot(arr17)

array([[10, 13],
       [28, 40]])

In [5]:
arr17 = np.arange(12).reshape(3,4)
arr17

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr17.max()

np.int64(11)

In [23]:
arr17.min()

np.int64(0)

In [25]:
arr17.min(axis=0)

array([0, 1, 2, 3])

In [26]:
arr17.min(axis=1)

array([0, 4, 8])

In [27]:
arr17.sum(axis=0)

array([12, 15, 18, 21])

In [28]:
arr17.sum(axis=1)

array([ 6, 22, 38])

In [29]:
arr17.mean()

np.float64(5.5)

In [30]:
arr17.std()

np.float64(3.452052529534663)

In [31]:
np.sin(arr17)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [33]:
np.median(arr17)

np.float64(5.5)

In [10]:
arr17

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr17.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
arr17.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
arr18 = np.arange(12,24).reshape(3,4)
arr18

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
np.hstack((arr17,arr18))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [19]:
np.vstack((arr17,arr18))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
np.hsplit(arr18,4)

[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [22]:
np.vsplit(arr18,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]